[book]
title = "Safe and Secure Coding in Rust"
authors = ["Lukasz Uszko"]
language = "en"

[build]
build-dir = "book"

[output.html.playground]
editable = true

[output.html.code.hidelines]
cpp = "//%"
