name: build_and_deploy_luk6xff's_blog_on_github_pages

# On every push this script is executed
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: publish_site
    runs-on: ubuntu-latest
    steps:
      - name: checkout_master
        uses: actions/checkout@v4
      - name: build_the_blog
        run: |
          chmod +x run.sh
          ./run.sh -b
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
